// <auto-generated />
using Kairos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Kairos.Migrations
{
    [DbContext(typeof(EventoContexto))]
    [Migration("20180125003607_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Kairos.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("activo");

                    b.Property<DateTime>("fecha");

                    b.Property<int>("idOrigen");

                    b.HasKey("Id");

                    b.HasIndex("idOrigen");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Kairos.Entidades.Origen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("activo");

                    b.Property<DateTime>("fechaCreacion");

                    b.Property<string>("nombreOrigen");

                    b.HasKey("Id");

                    b.ToTable("Origenes");
                });

            modelBuilder.Entity("Kairos.Entidades.Evento", b =>
                {
                    b.HasOne("Kairos.Entidades.Origen", "origen")
                        .WithMany("eventos")
                        .HasForeignKey("idOrigen")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
